name: public_release

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  PUBLIC_REPO_NAME: UnownHash/Xilriws-Public
  PUBLIC_IMAGE_NAME: unownhash/xilriws-public

jobs:
  release:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Generate requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt

      - name: Build with PyInstaller
        run: |
          poetry run pyinstaller app.py --onefile -n xilriws

      - name: Prepare Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update submodule
        run: |
          git submodule update --init --recursive

      - name: Commit maltelogin
        run: |
          git add .
          git commit -m "Update xilriws submodule" --allow-empty

      - name: Push maltelogin
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.XILRIWS_RELEASE_CLASSIC }}
          branch: ${{ github.ref }}

      - name: Copy xilriws files
        run: |
          cp dist/xilriws xilriws-public/xilriws

      - name: Commit Xilriws-Public
        run: |
          cd xilriws-public
          git add .
          git commit -m "Xilriws release"

      - name: Push Xilriws-Public
        uses: ad-m/github-push-action@master
        with:
          repository: UnownHash/Xilriws-Public
          directory: xilriws-public
          github_token: ${{ secrets.XILRIWS_RELEASE_CLASSIC }}

#  build-and-push-image:
#    runs-on: ubuntu-latest
#    permissions: read-all
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Log in to the Container registry
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.XILRIWS_RELEASE_CLASSIC }}
#      - name: Build and push Docker image to public repository
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: Dockerfile
#          platforms: linux/amd64,linux/arm64
#          push: true
#          build-args: |
#            VERSION=${{ inputs.tag }}
#          labels: |
#            package-name=xilriws-public
#          tags: |
#            ${{ env.REGISTRY }}/${{ env.PUBLIC_IMAGE_NAME }}:${{ steps.check_image_tag.outputs.imagetag }}
#            ${{ env.REGISTRY }}/${{ env.PUBLIC_IMAGE_NAME }}:${{ inputs.tag }}