name: public_release

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  PUBLIC_REPO_NAME: UnownHash/Xilriws-Public
  PUBLIC_IMAGE_NAME: unownhash/xilriws-public

jobs:
  release:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Generate requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt

      - name: Build with PyInstaller
        run: |
          poetry run pyinstaller app.py --onefile -n xilriws

      - name: Copy xilriws files
        run: |
          cp config.json.example dist/xilriws.json.example
          cp -r xilriws-public/* dist/
          mkdir dist/.github && mkdir dist/.github/workflows && cp -r xilriws-public/.github/workflows/* dist/.github/workflows

      - name: Push to Xilriws-Public
        uses: tech-thinker/push-to-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.XILRIWS_RELEASE_CLASSIC }}
        with:
          user-name: "github-actions[bot]"
          user-email: github-actions[bot]@users.noreply.github.com
          source-directory: "dist"
          commit-message: "Xilriws release"
          destination-github-username: "UnownHash"
          destination-repository-name: "Xilriws-Public"
          target-branch: main

#  build-and-push-image:
#    runs-on: ubuntu-latest
#    permissions: read-all
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Log in to the Container registry
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.XILRIWS_RELEASE_CLASSIC }}
#      - name: Build and push Docker image to public repository
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: Dockerfile
#          platforms: linux/amd64,linux/arm64
#          push: true
#          build-args: |
#            VERSION=${{ inputs.tag }}
#          labels: |
#            package-name=xilriws-public
#          tags: |
#            ${{ env.REGISTRY }}/${{ env.PUBLIC_IMAGE_NAME }}:${{ steps.check_image_tag.outputs.imagetag }}
#            ${{ env.REGISTRY }}/${{ env.PUBLIC_IMAGE_NAME }}:${{ inputs.tag }}